'use client';

import { useState } from 'react';
import type { InvitationPackage, InvitationParsed, QualityCheckResult, QualityControlConfig } from '@/lib/types';
import { PACKAGE_LABELS } from '@/lib/packages';
import { privacyReady, qualityChecksFor, qualityControl, qualityProgress, qualityReport, releaseReady, supportReady, updateQualityCheck } from '@/lib/quality-assurance';

const input = 'mt-1 w-full rounded-xl border border-gray-200 bg-white px-3 py-2 text-xs text-gray-700 outline-none focus:border-enkarta-gold font-outfit';
const packages: InvitationPackage[] = ['plus', 'premium', 'exclusive'];
const results: { value: QualityCheckResult; label: string; cls: string }[] = [
  { value: 'pending', label: 'Pendiente', cls: 'bg-gray-100 text-gray-500' },
  { value: 'passed', label: 'Aprobado', cls: 'bg-emerald-100 text-emerald-700' },
  { value: 'failed', label: 'Falló', cls: 'bg-red-100 text-red-700' },
  { value: 'not_applicable', label: 'No aplica', cls: 'bg-violet-100 text-violet-700' },
];

export default function QualityControlPanel({ data, onChange }: { data: InvitationParsed; onChange: (config: InvitationParsed['config']) => void }) {
  const contracted = data.config.package ?? 'exclusive';
  const [pkg, setPkg] = useState<InvitationPackage>(contracted);
  const control = qualityControl(data.config.qualityControl);
  const run = control.runs?.[pkg] ?? {};
  const progress = qualityProgress(control, pkg);
  const ready = releaseReady(control, contracted);
  const save = (next: QualityControlConfig) => onChange({ ...data.config, qualityControl: next });
  const updateRun = (patch: Partial<NonNullable<QualityControlConfig['runs']>[InvitationPackage]>) => save({ ...control, runs: { ...(control.runs ?? {}), [pkg]: { ...run, ...patch, updatedAt: new Date().toISOString() } } });
  const updateSupport = (patch: Partial<NonNullable<QualityControlConfig['support']>>) => save({ ...control, support: { ...(control.support ?? {}), ...patch } });
  const updatePrivacy = (patch: Partial<NonNullable<QualityControlConfig['privacy']>>) => save({ ...control, privacy: { ...(control.privacy ?? {}), ...patch } });
  const updateRelease = (patch: Partial<NonNullable<QualityControlConfig['release']>>) => save({ ...control, release: { ...(control.release ?? {}), ...patch } });
  const downloadReport = () => {
    const blob = new Blob([JSON.stringify(qualityReport(data), null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${data.slug}-aceptacion.json`; anchor.click(); URL.revokeObjectURL(url);
  };

  return <div className="space-y-5 p-4 font-outfit">
    <div className="overflow-hidden rounded-3xl bg-[linear-gradient(135deg,#28231d_0%,#645137_100%)] p-5 text-white shadow-lg">
      <p className="text-[10px] font-semibold uppercase tracking-[.2em] text-white/50">Fase 8 · Entrega segura</p>
      <div className="mt-2 flex items-end justify-between gap-4"><div><h2 className="font-playfair text-2xl">Centro de calidad</h2><p className="mt-1 max-w-sm text-xs leading-relaxed text-white/65">Evidencia el recorrido contratado, recuperación, soporte y publicación. Los checks manuales no se aprueban automáticamente.</p></div><div className="text-right"><strong className="font-playfair text-3xl">{qualityProgress(control, contracted).percent}%</strong><span className="block text-[9px] uppercase tracking-wider text-white/50">paquete contratado</span></div></div>
      <div className="mt-4 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#d4ad66] transition-all" style={{ width: `${qualityProgress(control, contracted).percent}%` }} /></div>
    </div>

    <section className="rounded-2xl border border-blue-100 bg-blue-50/60 p-3.5"><p className="text-xs font-semibold text-blue-800">Cobertura automatizada + aceptación humana</p><p className="mt-1 text-[11px] leading-relaxed text-blue-700/75">Las pruebas cubren paquetes, permisos, reintentos, revisiones y SQL. Cámara, dos dispositivos reales, conexión lenta y proveedores externos requieren evidencia manual en el entorno indicado.</p></section>

    <section className="space-y-3">
      <div className="flex items-center justify-between"><div><h3 className="text-sm font-semibold text-gray-800">Recorridos por paquete</h3><p className="text-[10px] text-gray-400">La invitación actual está contratada como {PACKAGE_LABELS[contracted]}.</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${progress.failed ? 'bg-red-100 text-red-700' : progress.percent === 100 ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>{progress.passed}/{progress.total}</span></div>
      <div className="grid grid-cols-3 gap-1.5 rounded-2xl bg-gray-100 p-1.5">{packages.map(item => <button key={item} type="button" onClick={() => setPkg(item)} className={`min-h-9 rounded-xl px-2 py-2 text-[10px] font-semibold ${pkg === item ? 'bg-white text-gray-800 shadow-sm' : 'text-gray-400'}`}>{PACKAGE_LABELS[item]} · {qualityProgress(control, item).percent}%</button>)}</div>
      <div className="grid grid-cols-2 gap-2"><label className="text-[10px] uppercase tracking-wider text-gray-400">Entorno<select className={input} value={run.environment ?? 'local'} onChange={event => updateRun({ environment: event.target.value as 'local' | 'preview' | 'production' })}><option value="local">Local</option><option value="preview">Vista previa</option><option value="production">Producción</option></select></label><label className="text-[10px] uppercase tracking-wider text-gray-400">URL comprobada<input className={input} value={run.url ?? ''} onChange={event => updateRun({ url: event.target.value })} placeholder="https://…" /></label></div>
      {qualityChecksFor(pkg).map(definition => {
        const record = run.checks?.[definition.id] ?? { result: 'pending' as const };
        return <details key={definition.id} className="overflow-hidden rounded-2xl border border-gray-200 bg-white">
          <summary className="flex cursor-pointer list-none items-center gap-3 p-3"><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-xl text-xs ${record.result === 'passed' ? 'bg-emerald-100 text-emerald-700' : record.result === 'failed' ? 'bg-red-100 text-red-700' : record.result === 'not_applicable' ? 'bg-violet-100 text-violet-700' : 'bg-gray-100 text-gray-400'}`}>{record.result === 'passed' ? '✓' : record.result === 'failed' ? '!' : '○'}</span><span className="min-w-0 flex-1"><span className="block text-xs font-semibold text-gray-700">{definition.label}</span><span className="block truncate text-[10px] text-gray-400">{definition.detail}</span></span><span className="text-[9px] uppercase text-gray-300">{definition.category}</span></summary>
          <div className="space-y-3 border-t border-gray-100 p-3"><div className="grid grid-cols-4 gap-1">{results.map(option => <button key={option.value} type="button" onClick={() => save(updateQualityCheck(control, pkg, definition.id, { ...record, result: option.value, checkedAt: option.value === 'pending' ? undefined : new Date().toISOString() }))} className={`min-h-9 rounded-lg px-1 py-2 text-[9px] font-semibold ${record.result === option.value ? option.cls : 'bg-gray-50 text-gray-300'}`}>{option.label}</button>)}</div><label className="block text-[10px] uppercase tracking-wider text-gray-400">Evidencia o incidencia<input className={input} value={record.evidence ?? ''} onChange={event => save(updateQualityCheck(control, pkg, definition.id, { ...record, evidence: event.target.value.slice(0, 500) }))} placeholder="Dispositivo, resultado, ticket o captura…" /></label>{record.checkedAt && <p className="text-[9px] text-gray-400">Comprobado: {new Date(record.checkedAt).toLocaleString('es-BO')}</p>}</div>
        </details>;
      })}
    </section>

    <section className="space-y-3 border-t border-gray-100 pt-5"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-gray-800">Soporte y entrega de instrucciones</h3><span className={`rounded-full px-2 py-1 text-[9px] font-semibold ${supportReady(control) ? 'bg-emerald-100 text-emerald-700' : 'bg-gray-100 text-gray-500'}`}>{supportReady(control) ? 'Completo' : 'Pendiente'}</span></div><div className="grid gap-2 sm:grid-cols-2"><label className="text-[10px] uppercase tracking-wider text-gray-400">Canal de soporte<input className={input} value={control.support?.channel ?? ''} onChange={event => updateSupport({ channel: event.target.value })} placeholder="WhatsApp / correo" /></label><label className="text-[10px] uppercase tracking-wider text-gray-400">Horario y días<input className={input} value={control.support?.availability ?? ''} onChange={event => updateSupport({ availability: event.target.value })} placeholder="Lun–Vie · 09:00–18:00" /></label><label className="text-[10px] uppercase tracking-wider text-gray-400">Primera respuesta · horas<input type="number" min={1} max={168} className={input} value={control.support?.firstResponseHours ?? ''} onChange={event => updateSupport({ firstResponseHours: Number(event.target.value) || undefined })} /></label><label className="text-[10px] uppercase tracking-wider text-gray-400">Responsable de escalamiento<input className={input} value={control.support?.escalationOwner ?? ''} onChange={event => updateSupport({ escalationOwner: event.target.value })} /></label><label className="text-[10px] uppercase tracking-wider text-gray-400">Soporte hasta<input type="date" className={input} value={control.support?.supportUntil ?? ''} onChange={event => updateSupport({ supportUntil: event.target.value })} /></label><label className="flex items-center gap-2 self-end rounded-xl border border-gray-100 bg-gray-50 p-2.5 text-[11px] text-gray-600"><input type="checkbox" className="h-4 w-4 accent-enkarta-gold" checked={control.support?.instructionsDelivered === true} onChange={event => updateSupport({ instructionsDelivered: event.target.checked })} />Guías entregadas a anfitrión y puerta</label></div></section>

    <section className="space-y-3 border-t border-gray-100 pt-5"><div className="flex items-center justify-between"><h3 className="text-sm font-semibold text-gray-800">Privacidad, respaldo y recuperación</h3><span className={`rounded-full px-2 py-1 text-[9px] font-semibold ${privacyReady(control) ? 'bg-emerald-100 text-emerald-700' : 'bg-gray-100 text-gray-500'}`}>{privacyReady(control) ? 'Completo' : 'Pendiente'}</span></div><div className="grid gap-2 sm:grid-cols-2"><label className="flex items-center gap-2 rounded-xl border border-gray-100 bg-gray-50 p-2.5 text-[11px] text-gray-600"><input type="checkbox" className="h-4 w-4 accent-enkarta-gold" checked={control.privacy?.retentionConfirmed === true} onChange={event => updatePrivacy({ retentionConfirmed: event.target.checked })} />Retención explicada y aceptada</label><label className="text-[10px] uppercase tracking-wider text-gray-400">Último respaldo<input type="datetime-local" className={input} value={control.privacy?.backupAt?.slice(0, 16) ?? ''} onChange={event => updatePrivacy({ backupAt: event.target.value ? new Date(event.target.value).toISOString() : undefined })} /></label><label className="text-[10px] uppercase tracking-wider text-gray-400">Restauración comprobada<input type="datetime-local" className={input} value={control.privacy?.restoreTestedAt?.slice(0, 16) ?? ''} onChange={event => updatePrivacy({ restoreTestedAt: event.target.value ? new Date(event.target.value).toISOString() : undefined })} /></label><label className="text-[10px] uppercase tracking-wider text-gray-400">Responsable de eliminación<input className={input} value={control.privacy?.deletionOwner ?? ''} onChange={event => updatePrivacy({ deletionOwner: event.target.value })} /></label><label className="text-[10px] uppercase tracking-wider text-gray-400 sm:col-span-2">Responsable de incidentes<input className={input} value={control.privacy?.incidentOwner ?? ''} onChange={event => updatePrivacy({ incidentOwner: event.target.value })} /></label></div></section>

    <section className="space-y-3 rounded-2xl border border-violet-100 bg-violet-50/50 p-3.5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-wider text-violet-500">Liberación por etapas</p><h3 className="mt-0.5 text-sm font-semibold text-violet-900">{control.release?.stage === 'production' ? 'Producción comprobada' : control.release?.stage === 'approved' ? 'Lista para promover' : control.release?.stage === 'preview' ? 'En vista previa' : 'Borrador'}</h3></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold ${ready ? 'bg-emerald-100 text-emerald-700' : 'bg-white text-violet-500'}`}>{ready ? 'Gate aprobado' : 'Gate cerrado'}</span></div><label className="text-[10px] uppercase tracking-wider text-violet-500">URL de vista previa<input className={input} value={control.release?.previewUrl ?? ''} onChange={event => updateRelease({ previewUrl: event.target.value, stage: event.target.value ? 'preview' : 'draft' })} /></label><div className="grid grid-cols-2 gap-2"><label className="text-[10px] uppercase tracking-wider text-violet-500">Versión para rollback<input className={input} value={control.release?.rollbackVersionId ?? ''} onChange={event => updateRelease({ rollbackVersionId: event.target.value })} placeholder="ID o etiqueta" /></label><label className="text-[10px] uppercase tracking-wider text-violet-500">Aprobado por<input className={input} value={control.release?.approvedBy ?? ''} onChange={event => updateRelease({ approvedBy: event.target.value })} /></label></div><textarea rows={2} className={input} value={control.release?.notes ?? ''} onChange={event => updateRelease({ notes: event.target.value.slice(0, 1000) })} placeholder="Riesgos conocidos, monitoreo y decisión de liberación…" />
      <div className="grid grid-cols-2 gap-2"><button type="button" disabled={!ready || !control.release?.approvedBy?.trim()} onClick={() => updateRelease({ stage: 'approved', approvedAt: new Date().toISOString() })} className="min-h-11 rounded-xl bg-violet-700 px-3 text-xs font-semibold text-white disabled:opacity-35">Aprobar entrega</button><button type="button" disabled={control.release?.stage !== 'approved' && control.release?.stage !== 'production'} onClick={() => updateRelease({ stage: 'production', productionCheckedAt: new Date().toISOString() })} className="min-h-11 rounded-xl border border-violet-200 bg-white px-3 text-xs font-semibold text-violet-700 disabled:opacity-35">Confirmar producción</button></div>
    </section>

    <button type="button" onClick={downloadReport} className="w-full rounded-xl border border-gray-200 bg-white py-3 text-xs font-semibold text-gray-600">Descargar evidencia de aceptación · JSON</button>
  </div>;
}
